#!/usr/bin/env bash

wmakerSessionComm="/usr/bin/wmaker-session-comm"
wmakerSessionBin="/usr/bin/wmaker"
wrapperScript="/usr/bin/startwmaker-community"

# Rename the original binary if it has not already been renamed
if [ -f "$wmakerSessionBin" ] && [ ! -f "$wmakerSessionComm" ]; then
	mv -f "$wmakerSessionBin" "$wmakerSessionComm"
fi

# Copy the wrapper script to replace wmaker-session
cp -f "$wrapperScript" "$wmakerSessionBin"
chmod +x "$wmakerSessionBin"
